### PR TITLE
Add working-directory input

### PR DESCRIPTION
**Pull request by curiositycasualty**
I'm not a fluent JS dev, this repo lacks tests, and I lack the know-how to test/run this locally.
Any help testing this would be appreciated.

### CODE REVIEW

**Comment by fregante** [comment]
Thank you for the PR! There are a couple of issues:

- I think the input is not the same as a ENV, so we need to use the correct way to use it
- it should probably be joined using path.join()
- I think it's best to default to "." and include the slash in the code, so the user can specify "pasta" instead of "pasta/"

**Comment by fregante** [comment]
Ping on this if you have time

**Comment by curiositycasualty** [comment]
> When you specify an input in a workflow file or use a default input value, GitHub creates an environment variable for the input with the name INPUT_<VARIABLE_NAME>. The environment variable created converts input names to uppercase letters and replaces spaces with _ characters.

~ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs

**Comment by curiositycasualty** [comment]
EH, looking back over it, I don't think my solution is great.
Here's an example of someone doing it in JS that might better fit the theme of this action:

https://github.com/dhet/scan-docker-tags-action/blob/7031c93488ec9059bc2b1fd38deff99c1e83cbcc/index.js#L2-L7

**Pull request closed without merging**
