### PR TITLE
Meta fixes

### PR DESCRIPTION
**Pull request by fregante**

### CODE REVIEW

**Comment by sitiom** [comment]
https://github.com/fregante/setup-git-user/blob/5ede2be584625f0c1f2a2ef6f6e4a8aa7665eb4c/.github/workflows/test.yml#L25

Putting the full ref qualifier `git push origin HEAD:refs/heads/testing-branch` makes it work.

**Comment by fregante** [comment]
No I don’t think that's the issue, the current code works on `push` events but not on `pull_request` events due to a permission issue. This sounds like GitHub is giving a token with reduced permissions to PRs, as expected.

**Comment by sitiom** [comment]
> https://github.com/fregante/setup-git-user/blob/5ede2be584625f0c1f2a2ef6f6e4a8aa7665eb4c/.github/workflows/test.yml#L25
> 
> Putting the full ref qualifier `git push origin HEAD:refs/heads/testing-branch` makes it work.

This works as tested here:

**Comment by fregante** [comment]
Can you send this PR from your fork? https://github.com/fregante/setup-git-user/pull/3/files

It's weird that they'd allow a fork to push to either repo

**Comment by sitiom** [comment]
> Can you send this PR from your fork? https://github.com/fregante/setup-git-user/pull/3/files
> 
> It's weird that they'd allow a fork to push to either repo

Yeah fails to work. The problem now is about remotes.

**Comment by fregante** [comment]
Yeah, so it defeats the purpose of being included for PRs.

Thanks for working with me on this

**Pull request merged**
