### PR TITLE
Use the actual GitHub Actions bot email

### PR DESCRIPTION
**Pull request by sitiom**
From https://github.community/t/github-actions-bot-email-address/17204/5

Github Actions commit

### CODE REVIEW

**Comment by fregante** [comment]
The current value already works like in your screenshot, as can be seen on https://github.com/fregante/daily-version-action/releases

Screen Shot 1

**Comment by sitiom** [comment]
> The current value already works like in your screenshot, as can be seen on https://github.com/fregante/daily-version-action/releases
> 
> Screen Shot 1

However, in the commits and the commit history, it doesn't show up as expected
Github Actions commit
It doesn't correctly point to the [github-actions](https://api.github.com/users/github-actions%5Bbot%5D) bot.

**Comment by fregante** [comment]
Indeed https://github.com/fregante/github-url-detection/commits/master

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
However this email doesn't work at all, as can be seen in the live demo. I think we should drop the `[bot]` part since it's likely irrelevant anyway, they only use the user ID

**Comment by sitiom** [comment]
> However this email doesn't work at all, as can be seen in the live demo. I think we should drop the `[bot]` part since it's likely irrelevant anyway, they only use the user ID

That still seems to work. Ok then.

**Comment by sitiom** [comment]
> However this email doesn't work at all, as can be seen in the live demo. I think we should drop the `[bot]` part since it's likely irrelevant anyway, they only use the user ID

What live demo are you talking about anyway, dependabot uses the same format on their commits.

dependabot commit

**Comment by fregante** [comment]
I wanted to ensure that my test still works on its own, so I opened https://github.com/fregante/setup-git-user/pull/2

You can see the workflow script here:  https://github.com/fregante/setup-git-user/actions/runs/758199116/workflow

```yml

      - name: Run Action
        uses: ./
      - name: Test the action by creating and deleting a commit
        run: |
          git commit --allow-empty --message 'git test'
          git push origin HEAD:testing-branch
          git push --delete origin testing-branch
```

It's a plain commit and push. In this PR it's failing because the user is being rejected

**Comment by sitiom** [comment]
> I wanted to ensure that my test still works on its own, so I opened #2
> 
> You can see the workflow script here: https://github.com/fregante/setup-git-user/actions/runs/758199116/workflow
> 
> ```yaml
>       - name: Run Action
>         uses: ./
>       - name: Test the action by creating and deleting a commit
>         run: |
>           git commit --allow-empty --message 'git test'
>           git push origin HEAD:testing-branch
>           git push --delete origin testing-branch
> ```
> 
> It's a plain commit and push. In this PR it's failing because the user is being rejected

Oh I see now, the `origin` remote is set to this repo instead of my fork, so it failed.

**Comment by fregante** [comment]
Actually no, it's failing in my PR too. I'm guessing that the PR test can't push back to the repo with the included token 🤔

**Comment by fregante** [comment]
I'll have to disable the test on PRs. Let me merge that PR with a fix and then I'll merge this

**Comment by fregante** [comment]
Indeed it works on `main`

**Pull request merged**
